### ISSUE TITLE
TODO: Problem 1 <r^2>

### ISSUE THREAD

**Issue by AkhilGhanta** [zehuachen/group1b-phy566-sp16-duke#3]
I've added the averaging component of problem 1. I'll have to drive back to school today, so can someone take care of the <x^2> and <r^2> parts? Thanks!

**Comment by zehuachen** [comment]
I'll do it. Please send a pull request to merge your branch to master. Note that the filename of the output image could be more meaningful, like "2d_random_walk.pdf".
